base_url = "https://c0np4nn4.github.io/apollo/"
title = "c0np4nn4"
build_search_index = true
generate_feed = true
compile_sass = true
minify_html = true

theme="apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = true
favicon = "/icon/favicon.png"
theme = "toggle" # light, dark, auto, toggle
# mathjax = true
# mathjax_dollar_inline_enable = true

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    # { name = "twitter", url = "https://twitter.com/", icon = "twitter" },
    { name = "github", url = "https://github.com/c0np4nn4", icon = "github" },
]

custom_css = []

# [extra.analytics]
# enabled = true
# goatcounter_user = "your_user"
# goatcounter_host = "example.com"    # default= goatcounter.com

