base_url = "https://c0np4nn4.github.io"

theme = "emily_zola_theme"

# The default language; used in feeds.
default_language = "en"

compile_sass = true

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]



[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true

# The theme to use for code highlighting.
# See below for list of allowed values.
# highlight_theme = ""

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = false

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = true
# Whether to include the rendered content of the page/section in the index
include_content = true

[extra]
# Author name, appears in footer.
emily_author = "c0np4nn4"

# Path to the header icon / favicon image.
# Please save image to static/images
emily_icon = "/images/logo.png"
emily_favicon = "/images/favicon.png"

# header icon width.
# height will be automatically rendered.
emily_iconsize = 70

# number of posts in index.html.
emily_indexposts = 3

# switch to dark-theme
emily_dark_mode = true

# show theme-toggler
emily_theme_toggler = true
