name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build

      - name: Delete gh-pages branch locally
        run: |
          git checkout --orphan temp-branch
          git branch -D gh-pages

      - name: Create a new gh-pages branch
        run: git checkout -b gh-pages

      - name: Copy built files to gh-pages
        run: cp -r ./* ./
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: '.'
          message: "Deploy to GitHub Pages"
          ref: "gh-pages"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: "gh-pages"
          force: true

