name: Deploy Quartz site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Copy files to gh-pages branch
        run: |
          ls -al
          rm -rf ./*
          cp -r ../public/* ./ # ../public로 경로를 지정해 줍니다.
          git add --all
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Deploy to GitHub Pages"
      
      - name: Push to gh-pages branch
        run: git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

